### ISSUE TITLE
Overflow Condition

### ISSUE THREAD

**Issue by abhisheietk** [abhisheietk/MyHDL_tutorial#4]
Overflow Condition (Why auto wrap doesn't work here, begin modbv types?)
Cyclic Queue, 1 Element taken as LOWER
```python
        if out_addr == (in_addr + modbv(1)[ADDRESS:])%DEPTH:
            inbusy.next = bool(1)
        else:
            inbusy.next = bool(0)
```

**Comment by abhisheietk** [comment]
UPPER is defined to maintain a cushion as its a cyclic queue. your Idea (no cushion) will definitely work with one type of clock  for read and write. But some designs required different clocks on both ports. In order to have a generic design i have used UPPER. If you define UPPER = 2**ADDRESS then cushion will become zero.

**Comment by Shilpimish** [comment]
Why auto wrap is not working here 
 if out_addr == (in_addr + modbv(1)[ADDRESS:])%DEPTH:
          
here the right value doesn't wrap.
